Better ScriptOutput error handling
When the external script fails, tell what command was run, and indent
the script's stderr.

This is actually all a ploy to add explicit stderr handling so that I
can suppress actual stderr output on Travis, (which doesn't have
netstat and therefore prints

    .............................................................Traceback (most recent call last):
      File "/home/travis/build/ProgrammersOfVilnius/pov-server-page/update_tcp_ports_html.py", line 284, in <module>
        main()
      File "/home/travis/build/ProgrammersOfVilnius/pov-server-page/update_tcp_ports_html.py", line 276, in main
        mapping = get_port_mapping(netstat())
      File "/home/travis/build/ProgrammersOfVilnius/pov-server-page/update_tcp_ports_html.py", line 212, in get_port_mapping
        for data in netstat_data:
      File "/home/travis/build/ProgrammersOfVilnius/pov-server-page/update_tcp_ports_html.py", line 91, in netstat
        with pipe('netstat', '-tnlvp') as f:
      File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
        return self.gen.next()
      File "/home/travis/build/ProgrammersOfVilnius/pov-server-page/update_tcp_ports_html.py", line 84, in pipe
        stderr=devnull).stdout as f:
      File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
        errread, errwrite)
      File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory
    ................................
    ----------------------------------------------------------------------
    Ran 93 tests in 0.217s