Fix Python 3 TypeError in replace_file()
Discovered by the newly-written tests for Builder.Template.

The error was

    Traceback (most recent call last):
      File "/home/mg/src/pov-server-page/tests/test_update_server_page.py", line 210, in test_Template
        Builder.Template('test.html.in').build(pathname, self.builder)
      File "/home/mg/src/pov-server-page/update_server_page.py", line 233, in build
        builder.replace_file(filename, self.marker, new_contents)
      File "/home/mg/src/pov-server-page/update_server_page.py", line 516, in replace_file
        if marker not in new_contents:
    TypeError: 'str' does not support the buffer interface