Fix Python 3 TypeError when using Builder.ScriptOutput
Discovered by the newly-written tests for Builder.ScriptOutput.

The error was

    Traceback (most recent call last):
      File "/home/mg/src/pov-server-page/tests/test_update_server_page.py", line 229, in test_ScriptOutput
        Builder.ScriptOutput('printf "%s\n" one {foo}').build(pathname, self.builder)
      File "/home/mg/src/pov-server-page/update_server_page.py", line 243, in build
        builder.replace_file(filename, self.marker, new_contents)
      File "/home/mg/src/pov-server-page/update_server_page.py", line 516, in replace_file
        if marker not in new_contents:
    TypeError: 'in <string>' requires string as left operand, not bytes