Skip tests while building the Debian package
Because python-mock in precise is too old:

    ======================================================================
    ERROR: test_compute_derived (tests.test_update_server_page.TestBuilderWithStdout)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/«PKGBUILDDIR»/tests/test_update_server_page.py", line 538, in test_compute_derived
        mock_datetime.now().__str__.return_value = '2015-11-01 14:35:03'
    TypeError: 'method-wrapper' object has only read-only attributes (assign to .return_value)

    ======================================================================
    ERROR: test_replace_file_error (tests.test_update_server_page.TestReplaceFile)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/«PKGBUILDDIR»/tests/test_update_server_page.py", line 170, in test_replace_file_error
        with mock.patch('update_server_page.open', self.raise_ioerror):
      File "/usr/lib/python2.7/dist-packages/mock.py", line 601, in __enter__
        original, local = self.get_original()
      File "/usr/lib/python2.7/dist-packages/mock.py", line 594, in get_original
        raise AttributeError("%s does not have the attribute %r" % (target, name))
    AttributeError: <module 'update_server_page' from '/«PKGBUILDDIR»/update_server_page.py'> does not have the attribute 'open'

    ======================================================================
    ERROR: test_get_html_cmdline (tests.test_update_tcp_ports_html.TestWithFakeEnvironment)
    ----------------------------------------------------------------------
    AttributeError: '_patch' object has no attribute 'is_local'

Also, something about the environment is weird: no root user in
/etc/passwd?

    ======================================================================
    FAIL: test_file_readable_to_bad_group (tests.test_update_server_page.TestBuilderFileReadability)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/«PKGBUILDDIR»/tests/test_update_server_page.py", line 577, in test_file_readable_to_bad_group
        self.assertTrue(file_readable_to(__file__, 'root', 'no-such-group'))
    AssertionError: False is not true

    ======================================================================
    FAIL: test_file_readable_to_bad_user (tests.test_update_server_page.TestBuilderFileReadability)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/«PKGBUILDDIR»/tests/test_update_server_page.py", line 573, in test_file_readable_to_bad_user
        self.assertTrue(file_readable_to(__file__, 'no-such-user', 'root'))
    AssertionError: False is not true

Also, no mount information either

    ..S...................................................................................FFF......df: cannot read table of mounted file systems: No such file or directory
    ......E...................df: cannot read table of mounted file systems: No such file or directory
    F......df: cannot read table of mounted file systems: No such file or directory
    F................E............EEEEEEEEEEEEEEEE

    ======================================================================
    FAIL: test_get_all_locations_real_df (tests.test_update_server_page.TestDiskUsageBuilderHelpers)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/«PKGBUILDDIR»/tests/test_update_server_page.py", line 341, in test_get_all_locations_real_df
        self.assertTrue('/' in locations, locations)
    AssertionError: False is not true

    ======================================================================
    FAIL: test_parse_all (tests.test_update_server_page.TestDiskUsageBuilderHelpers)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/«PKGBUILDDIR»/tests/test_update_server_page.py", line 372, in test_parse_all
        self.assertTrue('/' in locations, locations)
    AssertionError: False is not true